CREATE TABLE MEMBERS (
    id VARCHAR(50) PRIMARY KEY, 
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE CATEGORIES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    parent_id INT, 
    name VARCHAR(100) NOT NULL,
    FOREIGN KEY (parent_id) REFERENCES CATEGORIES(id)
);


CREATE TABLE PRODUCTS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_id INT NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 4) NOT NULL, 
    stock_quantity INT DEFAULT 0,
    FOREIGN KEY (category_id) REFERENCES CATEGORIES(id)
);

CREATE TABLE COUPONS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    member_id VARCHAR(50),
    coupon_code VARCHAR(50) NOT NULL,
    discount_amount DECIMAL(10, 4),
    valid_until DATETIME,
    FOREIGN KEY (member_id) REFERENCES MEMBERS(id)
);

CREATE TABLE ORDERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    member_id VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    total_amount DECIMAL(10, 4) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (member_id) REFERENCES MEMBERS(id)
);


CREATE TABLE ORDER_ITEMS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10, 4) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES ORDERS(id),
    FOREIGN KEY (product_id) REFERENCES PRODUCTS(id)
);

CREATE TABLE PAYMENTS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    amount DECIMAL(10, 4) NOT NULL,
    payment_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES ORDERS(id)
);