DROP TABLE IF EXISTS t24;

CREATE TABLE t24 (
    name VARCHAR(50)
);

INSERT INTO t24 VALUES ('A'), ('B'), ('C');

-- ❌ Oracle LISTAGG
SELECT LISTAGG(name, ',') WITHIN GROUP (ORDER BY name) FROM t24;

-- ✅ MySQL GROUP_CONCAT
SELECT GROUP_CONCAT(name ORDER BY name SEPARATOR ',') FROM t24;